name: test

on:
  push:
    branches-ignore:
      - master

env:
  NODE_ENV: test

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.2
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ hashFiles('**/package-lock.json') }}

      # run audit
      - run: npm audit

      # install dependencies
      - run: npm ci

      # run test
      - run: npm run test:ci
